object Main extends App {
    val board = new Board
    /*println(board.value(5, 2))
    println(board.value(4, 3))
    board.move(5, 2, 4, 3)
    println(board.value(5, 2))
    println(board.value(4, 3))
    board.move(2, 1, 3, 2)
    println(board.value(3, 2))
    println("strike test ")
    println("strike place " + board.value(2, 1))
    println("striked " + board.value(3, 2))
    println("striker" + board.value(4, 3))
    board.strikeOnce(4, 3, 2, 1)
    println("strike place " + board.value(2, 1))
    println("striked " + board.value(3, 2))
    println("striker " + board.value(4, 3))*/
    board.king(5, 4)
    println(board.value(5, 4))
    board.move(2, 1, 3, 2)
    println(board.value(3, 2))
    board.kingMove(5, 4, 3, 2)
    println(board.value(5, 4))
    println(board.value(3, 2))
}
